name: Deploy to Production
on:
  push:

jobs:
  sanity:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./sanity
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Build and deploy
        run: npm run deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
  nuxt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nuxt
    env:
      SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "./nuxt"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm generate
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./nuxt/.output/public --project-name ${{ secrets.CLOUDFLARE_PROJECT_NAME }} --branch ${{ github.ref_name }} --commit-hash ${{ github.sha }}
