name: Deploy to Production
on:
  push:

jobs:
  sanity:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sanity
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "./sanity/package-lock.json"
      - name: Install Dependencies
        run: npm install
      - name: Build and deploy
        run: npm run deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
  site:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    defaults:
      run:
        working-directory: ./astro
    env:
      SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
      SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
      SANITY_USE_CDN: false
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "./astro/pnpm-lock.yaml"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Restore astro build cache
        uses: actions/cache/restore@v4
        with:
          path: ./astro/.astroCache
          key: ${{ runner.os }}-astro
      - name: Build
        run: pnpm build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./astro/dist --project-name ${{ secrets.CLOUDFLARE_PROJECT_NAME }} --branch ${{ github.ref_name }} --commit-hash ${{ github.sha }}
      - name: Delete old astro build cache
        continue-on-error: true
        run: gh cache delete ${{ runner.os }}-astro
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save astro build cache
        uses: actions/cache/save@v4
        with:
          path: ./astro/.astroCache
          key: ${{ runner.os }}-astro
